#! /bin/bash

#. ~/.config/bspwm/panel/panel_colors
# Screen Padding
bspc config top_padding         38
#bspc config left_padding        10
#bspc config right_padding       10
#bspc config bottom_padding      16

bspc config border_width	    2
bspc config window_gap		    40

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d Term Browser File
#bspc monitor -d $(echo -e '\uf120') $(echo -e '\uf109') $(echo -e '\uf0ac') #$(echo -e '\uf001') $(echo -e '\uf141') $(echo -e '\uf07c')
#bspc monitor -d $(echo -e '\uf121') $(echo -e '\uf0c3')

#bspc config normal_border_color '#ebdbb2'
#bspc config focused_border_color '#fe8019'
#bspc config presel_border_color '#E1E5EA'
#bspc config normal_sticky_border_color '#2B2D37'
#bspc config focused_sticky_border_color '#5294E2'
#bspc config urgent_border_color '#CC575D'

bspc rule -a firefox follow=off floating=on desktop=^3
bspc rule -a mpv floating=on
bspc rule -a thunar floating=on focus=off desktop=^2
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad --sticky=on --floating=on


~/.config/bspwm/panel/panel &
sxhkd -c ~/.config/bspwm/key &
nitrogen --restore --set-scaled &
conky -c ~/.config/bspwm/status &
