#! /bin/zsh

PANEL_FIFO=/tmp/panel-fifo
PANEL_FONT_FAMILY="Source Code Pro for Powerline:size=9"
ICON_FONT="FontAwesome:size=9"
ICON_FONT2="fontcustom:size=9"
#export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
# xtitle -sf 'T%s' > "$PANEL_FIFO" &

# clock
while true;
	do
		echo 'C' $(date -u +"%l:%M %p");
	sleep 1.0;
done > "$PANEL_FIFO" &

# date
while true;
	do 
		echo 'D' $(date -u +'%a %b %d');
	sleep 1.0
done > $PANEL_FIFO &

# alsa volume
while true;
	do
		ALSA_VOLUME=$(amixer get Master | grep 'Front Left: Playback' | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //')
		ALSA_STATE=$(amixer get Master | grep 'Front Left: Playback' | grep -o '\[on]')

	if [ $ALSA_STATE ]
	then
	if [ $ALSA_VOLUME -ge 50 ]
	then
		echo V'\uf028' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -gt 0 -a $ALSA_VOLUME -lt 50 ]
	then
		echo V'\uf027' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -eq 0 ]
	then
		echo V'\uf026' $ALSA_VOLUME
	fi
	else
		echo V'\uf026' $ALSA_VOLUME
	fi
	sleep 1.0
done > $PANEL_FIFO &

# music controls
while true;
do
	SONG_NAME=$(mpc current)
	if [[ -z $(mpc current) ]]
	then
		# no music in playlist, or mpd is not running
		echo "R%{F$COLOR_INACTIVE_MONITOR_FG}%{T3}%{A:mpc listall | mpc add; mpc shuffle; mpc play:}%{A3:mopidy:}%{A}%{A}%{T1}%{F-}"
	else
		if [[ -n $(mpc status | grep paused) ]]
		then
			# music is paused
			echo "R%{F$COLOR_INACTIVE_MONITOR_FG}%{T3}%{A:mpc prev:} %{A}%{A:mpc play:}%{A3:mpc clear:}$SONG_NAME%{A}%{A}%{A:mpc next:} %{A}%{T1}%{F-}"
		else
			# music is playing
			echo "R%{F$COLOR_FOCUSED_OCCUPIED_FG}%{T3}%{A:mpc prev:} %{A}%{A:mpc pause:}%{A3:mpc clear:}$SONG_NAME%{A}%{A}%{A:mpc next:} %{A}%{T1}%{F-}"
		fi
	fi
	sleep 1.0
done > $PANEL_FIFO &


#. ~/.config/bspwm/panel/panel_colors

cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_bar | lemonbar -g 1326x28+20+20 -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -f "$ICON_FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -u 2 -p | zsh &

wait
